#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="aspnet-CivisSito1-20131208154650")]
public partial class DataClassesListaDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Definizioni metodo Extensibility
  partial void OnCreated();
  partial void InsertCategorie(Categorie instance);
  partial void UpdateCategorie(Categorie instance);
  partial void DeleteCategorie(Categorie instance);
  partial void InsertTipologie(Tipologie instance);
  partial void UpdateTipologie(Tipologie instance);
  partial void DeleteTipologie(Tipologie instance);
  partial void InsertStato(Stato instance);
  partial void UpdateStato(Stato instance);
  partial void DeleteStato(Stato instance);
  partial void InsertTable(Table instance);
  partial void UpdateTable(Table instance);
  partial void DeleteTable(Table instance);
  #endregion
	
	public DataClassesListaDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["aspnet_CivisSito1_20131208154650ConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesListaDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesListaDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesListaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesListaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<Categorie> Categorie
	{
		get
		{
			return this.GetTable<Categorie>();
		}
	}
	
	public System.Data.Linq.Table<Tipologie> Tipologie
	{
		get
		{
			return this.GetTable<Tipologie>();
		}
	}
	
	public System.Data.Linq.Table<Stato> Stato
	{
		get
		{
			return this.GetTable<Stato>();
		}
	}
	
	public System.Data.Linq.Table<Table> Table
	{
		get
		{
			return this.GetTable<Table>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Categorie")]
public partial class Categorie : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Id;
	
	private string _Categoria;
	
	private EntitySet<Table> _Table;
	
    #region Definizioni metodo Extensibility
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnCategoriaChanging(string value);
    partial void OnCategoriaChanged();
    #endregion
	
	public Categorie()
	{
		this._Table = new EntitySet<Table>(new Action<Table>(this.attach_Table), new Action<Table>(this.detach_Table));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Categoria", DbType="NChar(30)")]
	public string Categoria
	{
		get
		{
			return this._Categoria;
		}
		set
		{
			if ((this._Categoria != value))
			{
				this.OnCategoriaChanging(value);
				this.SendPropertyChanging();
				this._Categoria = value;
				this.SendPropertyChanged("Categoria");
				this.OnCategoriaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Categorie_Table", Storage="_Table", ThisKey="Id", OtherKey="Categoria")]
	public EntitySet<Table> Table
	{
		get
		{
			return this._Table;
		}
		set
		{
			this._Table.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_Table(Table entity)
	{
		this.SendPropertyChanging();
		entity.Categorie = this;
	}
	
	private void detach_Table(Table entity)
	{
		this.SendPropertyChanging();
		entity.Categorie = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tipologie")]
public partial class Tipologie : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Id;
	
	private string _Tipologia;
	
	private EntitySet<Table> _Table;
	
    #region Definizioni metodo Extensibility
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnTipologiaChanging(string value);
    partial void OnTipologiaChanged();
    #endregion
	
	public Tipologie()
	{
		this._Table = new EntitySet<Table>(new Action<Table>(this.attach_Table), new Action<Table>(this.detach_Table));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tipologia", DbType="NChar(30)")]
	public string Tipologia
	{
		get
		{
			return this._Tipologia;
		}
		set
		{
			if ((this._Tipologia != value))
			{
				this.OnTipologiaChanging(value);
				this.SendPropertyChanging();
				this._Tipologia = value;
				this.SendPropertyChanged("Tipologia");
				this.OnTipologiaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tipologie_Table", Storage="_Table", ThisKey="Id", OtherKey="Tipologia")]
	public EntitySet<Table> Table
	{
		get
		{
			return this._Table;
		}
		set
		{
			this._Table.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_Table(Table entity)
	{
		this.SendPropertyChanging();
		entity.Tipologie = this;
	}
	
	private void detach_Table(Table entity)
	{
		this.SendPropertyChanging();
		entity.Tipologie = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Stato")]
public partial class Stato : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Id;
	
	private string _Stato1;
	
	private EntitySet<Table> _Table;
	
    #region Definizioni metodo Extensibility
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnStato1Changing(string value);
    partial void OnStato1Changed();
    #endregion
	
	public Stato()
	{
		this._Table = new EntitySet<Table>(new Action<Table>(this.attach_Table), new Action<Table>(this.detach_Table));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Stato", Storage="_Stato1", DbType="VarChar(50)")]
	public string Stato1
	{
		get
		{
			return this._Stato1;
		}
		set
		{
			if ((this._Stato1 != value))
			{
				this.OnStato1Changing(value);
				this.SendPropertyChanging();
				this._Stato1 = value;
				this.SendPropertyChanged("Stato1");
				this.OnStato1Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Stato_Table", Storage="_Table", ThisKey="Id", OtherKey="Stato")]
	public EntitySet<Table> Table
	{
		get
		{
			return this._Table;
		}
		set
		{
			this._Table.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_Table(Table entity)
	{
		this.SendPropertyChanging();
		entity.Stato1 = this;
	}
	
	private void detach_Table(Table entity)
	{
		this.SendPropertyChanging();
		entity.Stato1 = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[Table]")]
public partial class Table : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Id;
	
	private System.Nullable<int> _Categoria;
	
	private System.Nullable<int> _Tipologia;
	
	private System.Nullable<int> _Stato;
	
	private System.Nullable<bool> _Libero;
	
	private System.Nullable<decimal> _Prezzo;
	
	private System.Nullable<int> _NLocali;
	
	private System.Nullable<int> _Superficie;
	
	private System.Nullable<decimal> _SpeseCondominiali;
	
	private System.Nullable<int> _NCamereLetto;
	
	private System.Nullable<int> _NSoggiorno;
	
	private System.Nullable<int> _AnnoCostruzione;
	
	private System.Nullable<int> _Piano;
	
	private System.Nullable<int> _TotPiani;
	
	private System.Nullable<byte> _ClasseEnergetica;
	
	private System.Nullable<byte> _EPI;
	
	private System.Nullable<byte> _Riscaldamento;
	
	private System.Nullable<byte> _Cucina;
	
	private System.Nullable<byte> _Box;
	
	private System.Nullable<int> _NPostiAuto;
	
	private System.Nullable<int> _Bagni;
	
	private System.Nullable<byte> _Giardino;
	
	private System.Nullable<byte> _Arredamento;
	
	private System.Nullable<byte> _Ingresso;
	
	private System.Nullable<byte> _Ripostiglio;
	
	private System.Nullable<byte> _Cantina;
	
	private System.Nullable<byte> _Mansarda;
	
	private System.Nullable<byte> _Taverna;
	
	private System.Nullable<byte> _InfissiInterni;
	
	private System.Nullable<byte> _ImpiantoTv;
	
	private string _Note;
	
	private string _Città;
	
	private string _Provincia;
	
	private System.Nullable<bool> _EsposizioneInt;
	
	private System.Nullable<bool> _EsposizioneEst;
	
	private System.Nullable<bool> _Condizionatore;
	
	private System.Nullable<bool> _Terrazzo;
	
	private System.Nullable<bool> _Balcone;
	
	private System.Nullable<bool> _Ascensore;
	
	private System.Nullable<bool> _Caminetto;
	
	private System.Nullable<bool> _PortaBlindata;
	
	private System.Nullable<bool> _Idromassaggio;
	
	private System.Nullable<bool> _ImpiantoAllarme;
	
	private System.Nullable<bool> _Piscina;
	
	private System.Nullable<bool> _CampoTennis;
	
	private System.Nullable<bool> _CancelloElettrico;
	
	private System.Nullable<bool> _Portiere;
	
	private System.Nullable<bool> _FibraOttica;
	
	private System.Nullable<bool> _VideoCitofono;
	
	private EntityRef<Categorie> _Categorie;
	
	private EntityRef<Tipologie> _Tipologie;
	
	private EntityRef<Stato> _Stato1;
	
    #region Definizioni metodo Extensibility
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnCategoriaChanging(System.Nullable<int> value);
    partial void OnCategoriaChanged();
    partial void OnTipologiaChanging(System.Nullable<int> value);
    partial void OnTipologiaChanged();
    partial void OnStatoChanging(System.Nullable<int> value);
    partial void OnStatoChanged();
    partial void OnLiberoChanging(System.Nullable<bool> value);
    partial void OnLiberoChanged();
    partial void OnPrezzoChanging(System.Nullable<decimal> value);
    partial void OnPrezzoChanged();
    partial void OnNLocaliChanging(System.Nullable<int> value);
    partial void OnNLocaliChanged();
    partial void OnSuperficieChanging(System.Nullable<int> value);
    partial void OnSuperficieChanged();
    partial void OnSpeseCondominialiChanging(System.Nullable<decimal> value);
    partial void OnSpeseCondominialiChanged();
    partial void OnNCamereLettoChanging(System.Nullable<int> value);
    partial void OnNCamereLettoChanged();
    partial void OnNSoggiornoChanging(System.Nullable<int> value);
    partial void OnNSoggiornoChanged();
    partial void OnAnnoCostruzioneChanging(System.Nullable<int> value);
    partial void OnAnnoCostruzioneChanged();
    partial void OnPianoChanging(System.Nullable<int> value);
    partial void OnPianoChanged();
    partial void OnTotPianiChanging(System.Nullable<int> value);
    partial void OnTotPianiChanged();
    partial void OnClasseEnergeticaChanging(System.Nullable<byte> value);
    partial void OnClasseEnergeticaChanged();
    partial void OnEPIChanging(System.Nullable<byte> value);
    partial void OnEPIChanged();
    partial void OnRiscaldamentoChanging(System.Nullable<byte> value);
    partial void OnRiscaldamentoChanged();
    partial void OnCucinaChanging(System.Nullable<byte> value);
    partial void OnCucinaChanged();
    partial void OnBoxChanging(System.Nullable<byte> value);
    partial void OnBoxChanged();
    partial void OnNPostiAutoChanging(System.Nullable<int> value);
    partial void OnNPostiAutoChanged();
    partial void OnBagniChanging(System.Nullable<int> value);
    partial void OnBagniChanged();
    partial void OnGiardinoChanging(System.Nullable<byte> value);
    partial void OnGiardinoChanged();
    partial void OnArredamentoChanging(System.Nullable<byte> value);
    partial void OnArredamentoChanged();
    partial void OnIngressoChanging(System.Nullable<byte> value);
    partial void OnIngressoChanged();
    partial void OnRipostiglioChanging(System.Nullable<byte> value);
    partial void OnRipostiglioChanged();
    partial void OnCantinaChanging(System.Nullable<byte> value);
    partial void OnCantinaChanged();
    partial void OnMansardaChanging(System.Nullable<byte> value);
    partial void OnMansardaChanged();
    partial void OnTavernaChanging(System.Nullable<byte> value);
    partial void OnTavernaChanged();
    partial void OnInfissiInterniChanging(System.Nullable<byte> value);
    partial void OnInfissiInterniChanged();
    partial void OnImpiantoTvChanging(System.Nullable<byte> value);
    partial void OnImpiantoTvChanged();
    partial void OnNoteChanging(string value);
    partial void OnNoteChanged();
    partial void OnCittàChanging(string value);
    partial void OnCittàChanged();
    partial void OnProvinciaChanging(string value);
    partial void OnProvinciaChanged();
    partial void OnEsposizioneIntChanging(System.Nullable<bool> value);
    partial void OnEsposizioneIntChanged();
    partial void OnEsposizioneEstChanging(System.Nullable<bool> value);
    partial void OnEsposizioneEstChanged();
    partial void OnCondizionatoreChanging(System.Nullable<bool> value);
    partial void OnCondizionatoreChanged();
    partial void OnTerrazzoChanging(System.Nullable<bool> value);
    partial void OnTerrazzoChanged();
    partial void OnBalconeChanging(System.Nullable<bool> value);
    partial void OnBalconeChanged();
    partial void OnAscensoreChanging(System.Nullable<bool> value);
    partial void OnAscensoreChanged();
    partial void OnCaminettoChanging(System.Nullable<bool> value);
    partial void OnCaminettoChanged();
    partial void OnPortaBlindataChanging(System.Nullable<bool> value);
    partial void OnPortaBlindataChanged();
    partial void OnIdromassaggioChanging(System.Nullable<bool> value);
    partial void OnIdromassaggioChanged();
    partial void OnImpiantoAllarmeChanging(System.Nullable<bool> value);
    partial void OnImpiantoAllarmeChanged();
    partial void OnPiscinaChanging(System.Nullable<bool> value);
    partial void OnPiscinaChanged();
    partial void OnCampoTennisChanging(System.Nullable<bool> value);
    partial void OnCampoTennisChanged();
    partial void OnCancelloElettricoChanging(System.Nullable<bool> value);
    partial void OnCancelloElettricoChanged();
    partial void OnPortiereChanging(System.Nullable<bool> value);
    partial void OnPortiereChanged();
    partial void OnFibraOtticaChanging(System.Nullable<bool> value);
    partial void OnFibraOtticaChanged();
    partial void OnVideoCitofonoChanging(System.Nullable<bool> value);
    partial void OnVideoCitofonoChanged();
    #endregion
	
	public Table()
	{
		this._Categorie = default(EntityRef<Categorie>);
		this._Tipologie = default(EntityRef<Tipologie>);
		this._Stato1 = default(EntityRef<Stato>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Categoria", DbType="Int")]
	public System.Nullable<int> Categoria
	{
		get
		{
			return this._Categoria;
		}
		set
		{
			if ((this._Categoria != value))
			{
				if (this._Categorie.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnCategoriaChanging(value);
				this.SendPropertyChanging();
				this._Categoria = value;
				this.SendPropertyChanged("Categoria");
				this.OnCategoriaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tipologia", DbType="Int")]
	public System.Nullable<int> Tipologia
	{
		get
		{
			return this._Tipologia;
		}
		set
		{
			if ((this._Tipologia != value))
			{
				if (this._Tipologie.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnTipologiaChanging(value);
				this.SendPropertyChanging();
				this._Tipologia = value;
				this.SendPropertyChanged("Tipologia");
				this.OnTipologiaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stato", DbType="Int")]
	public System.Nullable<int> Stato
	{
		get
		{
			return this._Stato;
		}
		set
		{
			if ((this._Stato != value))
			{
				if (this._Stato1.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnStatoChanging(value);
				this.SendPropertyChanging();
				this._Stato = value;
				this.SendPropertyChanged("Stato");
				this.OnStatoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Libero", DbType="Bit")]
	public System.Nullable<bool> Libero
	{
		get
		{
			return this._Libero;
		}
		set
		{
			if ((this._Libero != value))
			{
				this.OnLiberoChanging(value);
				this.SendPropertyChanging();
				this._Libero = value;
				this.SendPropertyChanged("Libero");
				this.OnLiberoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Prezzo", DbType="Money")]
	public System.Nullable<decimal> Prezzo
	{
		get
		{
			return this._Prezzo;
		}
		set
		{
			if ((this._Prezzo != value))
			{
				this.OnPrezzoChanging(value);
				this.SendPropertyChanging();
				this._Prezzo = value;
				this.SendPropertyChanged("Prezzo");
				this.OnPrezzoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NLocali", DbType="Int")]
	public System.Nullable<int> NLocali
	{
		get
		{
			return this._NLocali;
		}
		set
		{
			if ((this._NLocali != value))
			{
				this.OnNLocaliChanging(value);
				this.SendPropertyChanging();
				this._NLocali = value;
				this.SendPropertyChanged("NLocali");
				this.OnNLocaliChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Superficie", DbType="Int")]
	public System.Nullable<int> Superficie
	{
		get
		{
			return this._Superficie;
		}
		set
		{
			if ((this._Superficie != value))
			{
				this.OnSuperficieChanging(value);
				this.SendPropertyChanging();
				this._Superficie = value;
				this.SendPropertyChanged("Superficie");
				this.OnSuperficieChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SpeseCondominiali", DbType="Money")]
	public System.Nullable<decimal> SpeseCondominiali
	{
		get
		{
			return this._SpeseCondominiali;
		}
		set
		{
			if ((this._SpeseCondominiali != value))
			{
				this.OnSpeseCondominialiChanging(value);
				this.SendPropertyChanging();
				this._SpeseCondominiali = value;
				this.SendPropertyChanged("SpeseCondominiali");
				this.OnSpeseCondominialiChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NCamereLetto", DbType="Int")]
	public System.Nullable<int> NCamereLetto
	{
		get
		{
			return this._NCamereLetto;
		}
		set
		{
			if ((this._NCamereLetto != value))
			{
				this.OnNCamereLettoChanging(value);
				this.SendPropertyChanging();
				this._NCamereLetto = value;
				this.SendPropertyChanged("NCamereLetto");
				this.OnNCamereLettoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NSoggiorno", DbType="Int")]
	public System.Nullable<int> NSoggiorno
	{
		get
		{
			return this._NSoggiorno;
		}
		set
		{
			if ((this._NSoggiorno != value))
			{
				this.OnNSoggiornoChanging(value);
				this.SendPropertyChanging();
				this._NSoggiorno = value;
				this.SendPropertyChanged("NSoggiorno");
				this.OnNSoggiornoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnnoCostruzione", DbType="Int")]
	public System.Nullable<int> AnnoCostruzione
	{
		get
		{
			return this._AnnoCostruzione;
		}
		set
		{
			if ((this._AnnoCostruzione != value))
			{
				this.OnAnnoCostruzioneChanging(value);
				this.SendPropertyChanging();
				this._AnnoCostruzione = value;
				this.SendPropertyChanged("AnnoCostruzione");
				this.OnAnnoCostruzioneChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Piano", DbType="Int")]
	public System.Nullable<int> Piano
	{
		get
		{
			return this._Piano;
		}
		set
		{
			if ((this._Piano != value))
			{
				this.OnPianoChanging(value);
				this.SendPropertyChanging();
				this._Piano = value;
				this.SendPropertyChanged("Piano");
				this.OnPianoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotPiani", DbType="Int")]
	public System.Nullable<int> TotPiani
	{
		get
		{
			return this._TotPiani;
		}
		set
		{
			if ((this._TotPiani != value))
			{
				this.OnTotPianiChanging(value);
				this.SendPropertyChanging();
				this._TotPiani = value;
				this.SendPropertyChanged("TotPiani");
				this.OnTotPianiChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClasseEnergetica", DbType="TinyInt")]
	public System.Nullable<byte> ClasseEnergetica
	{
		get
		{
			return this._ClasseEnergetica;
		}
		set
		{
			if ((this._ClasseEnergetica != value))
			{
				this.OnClasseEnergeticaChanging(value);
				this.SendPropertyChanging();
				this._ClasseEnergetica = value;
				this.SendPropertyChanged("ClasseEnergetica");
				this.OnClasseEnergeticaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EPI", DbType="TinyInt")]
	public System.Nullable<byte> EPI
	{
		get
		{
			return this._EPI;
		}
		set
		{
			if ((this._EPI != value))
			{
				this.OnEPIChanging(value);
				this.SendPropertyChanging();
				this._EPI = value;
				this.SendPropertyChanged("EPI");
				this.OnEPIChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Riscaldamento", DbType="TinyInt")]
	public System.Nullable<byte> Riscaldamento
	{
		get
		{
			return this._Riscaldamento;
		}
		set
		{
			if ((this._Riscaldamento != value))
			{
				this.OnRiscaldamentoChanging(value);
				this.SendPropertyChanging();
				this._Riscaldamento = value;
				this.SendPropertyChanged("Riscaldamento");
				this.OnRiscaldamentoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cucina", DbType="TinyInt")]
	public System.Nullable<byte> Cucina
	{
		get
		{
			return this._Cucina;
		}
		set
		{
			if ((this._Cucina != value))
			{
				this.OnCucinaChanging(value);
				this.SendPropertyChanging();
				this._Cucina = value;
				this.SendPropertyChanged("Cucina");
				this.OnCucinaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Box", DbType="TinyInt")]
	public System.Nullable<byte> Box
	{
		get
		{
			return this._Box;
		}
		set
		{
			if ((this._Box != value))
			{
				this.OnBoxChanging(value);
				this.SendPropertyChanging();
				this._Box = value;
				this.SendPropertyChanged("Box");
				this.OnBoxChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NPostiAuto", DbType="Int")]
	public System.Nullable<int> NPostiAuto
	{
		get
		{
			return this._NPostiAuto;
		}
		set
		{
			if ((this._NPostiAuto != value))
			{
				this.OnNPostiAutoChanging(value);
				this.SendPropertyChanging();
				this._NPostiAuto = value;
				this.SendPropertyChanged("NPostiAuto");
				this.OnNPostiAutoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bagni", DbType="Int")]
	public System.Nullable<int> Bagni
	{
		get
		{
			return this._Bagni;
		}
		set
		{
			if ((this._Bagni != value))
			{
				this.OnBagniChanging(value);
				this.SendPropertyChanging();
				this._Bagni = value;
				this.SendPropertyChanged("Bagni");
				this.OnBagniChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Giardino", DbType="TinyInt")]
	public System.Nullable<byte> Giardino
	{
		get
		{
			return this._Giardino;
		}
		set
		{
			if ((this._Giardino != value))
			{
				this.OnGiardinoChanging(value);
				this.SendPropertyChanging();
				this._Giardino = value;
				this.SendPropertyChanged("Giardino");
				this.OnGiardinoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Arredamento", DbType="TinyInt")]
	public System.Nullable<byte> Arredamento
	{
		get
		{
			return this._Arredamento;
		}
		set
		{
			if ((this._Arredamento != value))
			{
				this.OnArredamentoChanging(value);
				this.SendPropertyChanging();
				this._Arredamento = value;
				this.SendPropertyChanged("Arredamento");
				this.OnArredamentoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ingresso", DbType="TinyInt")]
	public System.Nullable<byte> Ingresso
	{
		get
		{
			return this._Ingresso;
		}
		set
		{
			if ((this._Ingresso != value))
			{
				this.OnIngressoChanging(value);
				this.SendPropertyChanging();
				this._Ingresso = value;
				this.SendPropertyChanged("Ingresso");
				this.OnIngressoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ripostiglio", DbType="TinyInt")]
	public System.Nullable<byte> Ripostiglio
	{
		get
		{
			return this._Ripostiglio;
		}
		set
		{
			if ((this._Ripostiglio != value))
			{
				this.OnRipostiglioChanging(value);
				this.SendPropertyChanging();
				this._Ripostiglio = value;
				this.SendPropertyChanged("Ripostiglio");
				this.OnRipostiglioChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cantina", DbType="TinyInt")]
	public System.Nullable<byte> Cantina
	{
		get
		{
			return this._Cantina;
		}
		set
		{
			if ((this._Cantina != value))
			{
				this.OnCantinaChanging(value);
				this.SendPropertyChanging();
				this._Cantina = value;
				this.SendPropertyChanged("Cantina");
				this.OnCantinaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mansarda", DbType="TinyInt")]
	public System.Nullable<byte> Mansarda
	{
		get
		{
			return this._Mansarda;
		}
		set
		{
			if ((this._Mansarda != value))
			{
				this.OnMansardaChanging(value);
				this.SendPropertyChanging();
				this._Mansarda = value;
				this.SendPropertyChanged("Mansarda");
				this.OnMansardaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Taverna", DbType="TinyInt")]
	public System.Nullable<byte> Taverna
	{
		get
		{
			return this._Taverna;
		}
		set
		{
			if ((this._Taverna != value))
			{
				this.OnTavernaChanging(value);
				this.SendPropertyChanging();
				this._Taverna = value;
				this.SendPropertyChanged("Taverna");
				this.OnTavernaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InfissiInterni", DbType="TinyInt")]
	public System.Nullable<byte> InfissiInterni
	{
		get
		{
			return this._InfissiInterni;
		}
		set
		{
			if ((this._InfissiInterni != value))
			{
				this.OnInfissiInterniChanging(value);
				this.SendPropertyChanging();
				this._InfissiInterni = value;
				this.SendPropertyChanged("InfissiInterni");
				this.OnInfissiInterniChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImpiantoTv", DbType="TinyInt")]
	public System.Nullable<byte> ImpiantoTv
	{
		get
		{
			return this._ImpiantoTv;
		}
		set
		{
			if ((this._ImpiantoTv != value))
			{
				this.OnImpiantoTvChanging(value);
				this.SendPropertyChanging();
				this._ImpiantoTv = value;
				this.SendPropertyChanged("ImpiantoTv");
				this.OnImpiantoTvChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Note", DbType="Text", UpdateCheck=UpdateCheck.Never)]
	public string Note
	{
		get
		{
			return this._Note;
		}
		set
		{
			if ((this._Note != value))
			{
				this.OnNoteChanging(value);
				this.SendPropertyChanging();
				this._Note = value;
				this.SendPropertyChanged("Note");
				this.OnNoteChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Città", DbType="VarChar(50)")]
	public string Città
	{
		get
		{
			return this._Città;
		}
		set
		{
			if ((this._Città != value))
			{
				this.OnCittàChanging(value);
				this.SendPropertyChanging();
				this._Città = value;
				this.SendPropertyChanged("Città");
				this.OnCittàChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Provincia", DbType="NChar(2)")]
	public string Provincia
	{
		get
		{
			return this._Provincia;
		}
		set
		{
			if ((this._Provincia != value))
			{
				this.OnProvinciaChanging(value);
				this.SendPropertyChanging();
				this._Provincia = value;
				this.SendPropertyChanged("Provincia");
				this.OnProvinciaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EsposizioneInt", DbType="Bit")]
	public System.Nullable<bool> EsposizioneInt
	{
		get
		{
			return this._EsposizioneInt;
		}
		set
		{
			if ((this._EsposizioneInt != value))
			{
				this.OnEsposizioneIntChanging(value);
				this.SendPropertyChanging();
				this._EsposizioneInt = value;
				this.SendPropertyChanged("EsposizioneInt");
				this.OnEsposizioneIntChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EsposizioneEst", DbType="Bit")]
	public System.Nullable<bool> EsposizioneEst
	{
		get
		{
			return this._EsposizioneEst;
		}
		set
		{
			if ((this._EsposizioneEst != value))
			{
				this.OnEsposizioneEstChanging(value);
				this.SendPropertyChanging();
				this._EsposizioneEst = value;
				this.SendPropertyChanged("EsposizioneEst");
				this.OnEsposizioneEstChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Condizionatore", DbType="Bit")]
	public System.Nullable<bool> Condizionatore
	{
		get
		{
			return this._Condizionatore;
		}
		set
		{
			if ((this._Condizionatore != value))
			{
				this.OnCondizionatoreChanging(value);
				this.SendPropertyChanging();
				this._Condizionatore = value;
				this.SendPropertyChanged("Condizionatore");
				this.OnCondizionatoreChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Terrazzo", DbType="Bit")]
	public System.Nullable<bool> Terrazzo
	{
		get
		{
			return this._Terrazzo;
		}
		set
		{
			if ((this._Terrazzo != value))
			{
				this.OnTerrazzoChanging(value);
				this.SendPropertyChanging();
				this._Terrazzo = value;
				this.SendPropertyChanged("Terrazzo");
				this.OnTerrazzoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Balcone", DbType="Bit")]
	public System.Nullable<bool> Balcone
	{
		get
		{
			return this._Balcone;
		}
		set
		{
			if ((this._Balcone != value))
			{
				this.OnBalconeChanging(value);
				this.SendPropertyChanging();
				this._Balcone = value;
				this.SendPropertyChanged("Balcone");
				this.OnBalconeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ascensore", DbType="Bit")]
	public System.Nullable<bool> Ascensore
	{
		get
		{
			return this._Ascensore;
		}
		set
		{
			if ((this._Ascensore != value))
			{
				this.OnAscensoreChanging(value);
				this.SendPropertyChanging();
				this._Ascensore = value;
				this.SendPropertyChanged("Ascensore");
				this.OnAscensoreChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Caminetto", DbType="Bit")]
	public System.Nullable<bool> Caminetto
	{
		get
		{
			return this._Caminetto;
		}
		set
		{
			if ((this._Caminetto != value))
			{
				this.OnCaminettoChanging(value);
				this.SendPropertyChanging();
				this._Caminetto = value;
				this.SendPropertyChanged("Caminetto");
				this.OnCaminettoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PortaBlindata", DbType="Bit")]
	public System.Nullable<bool> PortaBlindata
	{
		get
		{
			return this._PortaBlindata;
		}
		set
		{
			if ((this._PortaBlindata != value))
			{
				this.OnPortaBlindataChanging(value);
				this.SendPropertyChanging();
				this._PortaBlindata = value;
				this.SendPropertyChanged("PortaBlindata");
				this.OnPortaBlindataChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Idromassaggio", DbType="Bit")]
	public System.Nullable<bool> Idromassaggio
	{
		get
		{
			return this._Idromassaggio;
		}
		set
		{
			if ((this._Idromassaggio != value))
			{
				this.OnIdromassaggioChanging(value);
				this.SendPropertyChanging();
				this._Idromassaggio = value;
				this.SendPropertyChanged("Idromassaggio");
				this.OnIdromassaggioChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImpiantoAllarme", DbType="Bit")]
	public System.Nullable<bool> ImpiantoAllarme
	{
		get
		{
			return this._ImpiantoAllarme;
		}
		set
		{
			if ((this._ImpiantoAllarme != value))
			{
				this.OnImpiantoAllarmeChanging(value);
				this.SendPropertyChanging();
				this._ImpiantoAllarme = value;
				this.SendPropertyChanged("ImpiantoAllarme");
				this.OnImpiantoAllarmeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Piscina", DbType="Bit")]
	public System.Nullable<bool> Piscina
	{
		get
		{
			return this._Piscina;
		}
		set
		{
			if ((this._Piscina != value))
			{
				this.OnPiscinaChanging(value);
				this.SendPropertyChanging();
				this._Piscina = value;
				this.SendPropertyChanged("Piscina");
				this.OnPiscinaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CampoTennis", DbType="Bit")]
	public System.Nullable<bool> CampoTennis
	{
		get
		{
			return this._CampoTennis;
		}
		set
		{
			if ((this._CampoTennis != value))
			{
				this.OnCampoTennisChanging(value);
				this.SendPropertyChanging();
				this._CampoTennis = value;
				this.SendPropertyChanged("CampoTennis");
				this.OnCampoTennisChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CancelloElettrico", DbType="Bit")]
	public System.Nullable<bool> CancelloElettrico
	{
		get
		{
			return this._CancelloElettrico;
		}
		set
		{
			if ((this._CancelloElettrico != value))
			{
				this.OnCancelloElettricoChanging(value);
				this.SendPropertyChanging();
				this._CancelloElettrico = value;
				this.SendPropertyChanged("CancelloElettrico");
				this.OnCancelloElettricoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Portiere", DbType="Bit")]
	public System.Nullable<bool> Portiere
	{
		get
		{
			return this._Portiere;
		}
		set
		{
			if ((this._Portiere != value))
			{
				this.OnPortiereChanging(value);
				this.SendPropertyChanging();
				this._Portiere = value;
				this.SendPropertyChanged("Portiere");
				this.OnPortiereChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FibraOttica", DbType="Bit")]
	public System.Nullable<bool> FibraOttica
	{
		get
		{
			return this._FibraOttica;
		}
		set
		{
			if ((this._FibraOttica != value))
			{
				this.OnFibraOtticaChanging(value);
				this.SendPropertyChanging();
				this._FibraOttica = value;
				this.SendPropertyChanged("FibraOttica");
				this.OnFibraOtticaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VideoCitofono", DbType="Bit")]
	public System.Nullable<bool> VideoCitofono
	{
		get
		{
			return this._VideoCitofono;
		}
		set
		{
			if ((this._VideoCitofono != value))
			{
				this.OnVideoCitofonoChanging(value);
				this.SendPropertyChanging();
				this._VideoCitofono = value;
				this.SendPropertyChanged("VideoCitofono");
				this.OnVideoCitofonoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Categorie_Table", Storage="_Categorie", ThisKey="Categoria", OtherKey="Id", IsForeignKey=true)]
	public Categorie Categorie
	{
		get
		{
			return this._Categorie.Entity;
		}
		set
		{
			Categorie previousValue = this._Categorie.Entity;
			if (((previousValue != value) 
						|| (this._Categorie.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._Categorie.Entity = null;
					previousValue.Table.Remove(this);
				}
				this._Categorie.Entity = value;
				if ((value != null))
				{
					value.Table.Add(this);
					this._Categoria = value.Id;
				}
				else
				{
					this._Categoria = default(Nullable<int>);
				}
				this.SendPropertyChanged("Categorie");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tipologie_Table", Storage="_Tipologie", ThisKey="Tipologia", OtherKey="Id", IsForeignKey=true)]
	public Tipologie Tipologie
	{
		get
		{
			return this._Tipologie.Entity;
		}
		set
		{
			Tipologie previousValue = this._Tipologie.Entity;
			if (((previousValue != value) 
						|| (this._Tipologie.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._Tipologie.Entity = null;
					previousValue.Table.Remove(this);
				}
				this._Tipologie.Entity = value;
				if ((value != null))
				{
					value.Table.Add(this);
					this._Tipologia = value.Id;
				}
				else
				{
					this._Tipologia = default(Nullable<int>);
				}
				this.SendPropertyChanged("Tipologie");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Stato_Table", Storage="_Stato1", ThisKey="Stato", OtherKey="Id", IsForeignKey=true)]
	public Stato Stato1
	{
		get
		{
			return this._Stato1.Entity;
		}
		set
		{
			Stato previousValue = this._Stato1.Entity;
			if (((previousValue != value) 
						|| (this._Stato1.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._Stato1.Entity = null;
					previousValue.Table.Remove(this);
				}
				this._Stato1.Entity = value;
				if ((value != null))
				{
					value.Table.Add(this);
					this._Stato = value.Id;
				}
				else
				{
					this._Stato = default(Nullable<int>);
				}
				this.SendPropertyChanged("Stato1");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
